### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by AmrinKareem** [mgupta70/PID_Symbol_Detection#1]
Hi @mgupta70, thank you for sharing your amazing work! 
I'd like to request you to add some details regarding steps for training, folder structure of train and test data, code for label transfer, as well as the config files, if possible.
Thanks for your time :)

**Comment by mgupta70** [comment]
Hi @AmrinKareem, folder structure for both train and test: 
![folder_structure](https://github.com/user-attachments/assets/f38112eb-2fd2-4bce-9b0f-2dcf96b8ba61)

I will share the code for label transfer by the end of this week! (It is simply a classifier that runs over Yolo predictions)

By the way, I’d be interested to know what you're working on with P&IDs.

**Comment by AmrinKareem** [comment]
Thank you, Mohit! This is very helpful :) 

I am working on a personal project trying to combine LLMs and engineering diagrams. I came across your code so wanted to see if it would be a good fit.

**Comment by mgupta70** [comment]
It sounds very promising and useful for engineers. Engineering drawings require certain expertise to 'read' them and perform domain-specific tasks. Connecting with some domain experts might prove beneficial to defining objectives for combining LLMs with Vision models. 

I am also working on somewhat similar aspect - information extraction from complex text prompts (sort of VQA). If you are interested, I would not mind having a private discussion over zoom. Email: mgupta70@asu.edu

**Comment by mgupta70** [comment]
A rough code for label transfer is uploaded in **Draft** folder. It is not the latest version (I was unable to find it) or the cleanest code. But it will give you some more information on the implementation of Stage-2.

**Comment by mgupta70** [comment]
Hi @AmrinKareem, if you are still working in this area: 
config files are now present in [src/pipeline/configs](https://github.com/mgupta70/PID_Symbol_Detection/tree/main/src/pipeline/configs) folder

Steps to run the code for training/inference/evaluation are present in [src/run_pipeline.py](https://github.com/mgupta70/PID_Symbol_Detection/tree/main/src/run_pipeline.py)
