### ISSUE TITLE
use of “Stage2_label_transfer_utils.py”

### ISSUE THREAD

**Issue by Airex-ai** [mgupta70/PID_Symbol_Detection#2]
Hi @mgupta70, thank you for sharing your amazing work!
I'd like to ask you how to use “Stage2_label_transfer_utils.py” to transfer labels as README.md explains, if possible.
Thanks for your time :)

**Comment by mgupta70** [comment]
Hi, I have created a Draft folder in the project repo.
In this, I have uploaded a rough version of Stage 2 as a Jupyter notebook.  I was unable to find my final version of Stage 2 and this rough version is all I could find. The code is not all clean. Sorry about that. Also, it does not use all the functions in Stage2_label_transfer_utils.py. But if you go through it, you should be able to understand it and create a version of Stage-2 on your own.

**Comment by mgupta70** [comment]
Hi @Airex-ai, if you are still working in this area, details regarding stage 2 have been updated. Please check [src/pipeline](https://github.com/mgupta70/PID_Symbol_Detection/tree/main/src/pipeline)
